### PR TITLE
[RFC] Syscall test app

### PR DESCRIPTION
**Pull request by frdeso**
Add `gen-syscall-events` test app to reliably generate syscalls and update syscall regression tests.

The `gen-syscall-events` program starts and waits for a signal before executing three syscalls and exiting. This test app is now used for the syscall regression tests in conjunction with the PID tracker to only trace the syscalls executed by our test app.

### CODE REVIEW

**Comment by frdeso** [comment]
In a similar PR, @compudj pointed out that there is a race in how the events are generated that could make the tests unreliable. I will have make the necessary changes and update this PR.

**Comment by jgalar** [comment]
Do you have an update on this PR?

**Comment by frdeso** [comment]
I updated and rebased this pull request. It's now ready for review.

**Comment by jgalar** [comment]
Rebased on master here:
https://github.com/jgalar/lttng-tools/commits/syscall-testapp

However, the test seems to fail on my machine. Can you check on yours?

**Comment by frdeso** [comment]
It does work on my machine. Let's investigate.

**Comment by jgalar** [comment]
Okay, strange... I'm looking into it.

**Comment by jgalar** [comment]
Turns out that my libc (2.26) actually calls `openat(AT_FDCWD, pathname, ...)` when `open()` is used. As discussed, let's change the test to use a raw syscall.

**Comment by jgalar** [comment]
Merged, thanks!

**Pull request closed without merging**
