### PR TITLE
Redirect spawned sessiond's stdout/err to /dev/null

### PR DESCRIPTION
**Pull request by eepp**
See commit message of 195c706.

This is more an RFC. What do you think?

### CODE REVIEW

**Comment by eepp** [comment]
I'm still having issues with stderr. I save it in case `exec()` fails (`saved_stderr` in fafc2a5), but then I get the same problem; `lttng create` with a redirected stderr hangs, e.g.:

    lttng create 2>&1 | wc

@simark suggested setting the `FD_CLOEXEC` flag on stderr, but then the file descriptor would be closed for the session daemon (whereas in my case it's open and directed to `/dev/null`), which would make calls to `fprintf(stderr, ...)` fail.

See:

    #include <stdio.h>
    #include <stdlib.h>
    #include <unistd.h>
    
    int main(void)
    {
    	close(2);
    	printf("%d\n", fprintf(stderr, "hello\n"));
    
    	return 0;
    }

which prints `-1`.

**Comment by simark** [comment]
I was thinking setting CLOEXEC on saved_stderr, as this seems to be the problematic fd. It stays open in lttng-sessiond, and connected to wc's stdin in `lttng create | wc`.

**Comment by eepp** [comment]
I see. No they don't share flags (from `dup(2)`):

> The two descriptors do not share file descriptor flags (the close-on-
> exec flag).  The close-on-exec flag (FD_CLOEXEC; see fcntl(2)) for
> the duplicate descriptor is off.

**Comment by eepp** [comment]
Have a look at e2684a7. It makes use of sessiond's `--dameonize` option, which closes its open FDs like a good citizen. `SIGCHLD` will be received when sessiond exits, but if it exits successfully, then we know it's running, so `lttng` may continue with the `create` command.

**Comment by jgalar** [comment]
"Better solution" does look like a better solution. :+1:

**Comment by eepp** [comment]
Closing to keep this log. See #28.

**Pull request closed without merging**
