### PR TITLE
Add time suffixes

### PR DESCRIPTION
**Pull request by simark**

### CODE REVIEW

**Comment by jgalar** [comment]
Closing for lack of activity.

**Comment by jgalar** [comment]
Hey @simark, just so you know, I merged this and it'll be part of 2.11.
It's used for the `enable-channel`, `create`, and `enable-rotation` commands.

Thanks :smiley:

**Comment by simark** [comment]
Re-reading the patch description after all this time, I now wonder why we did not choose `32us`, `32ms`, `32s`.  It's much more obvious what `32ms` is, compared to `32m`.  Maybe both forms could be accepted too.

**Comment by simark** [comment]
Ah nevermind, I see that you've pimped up the code to add that!

**Pull request closed without merging**
