### PR TITLE
configure.ac: add --disable-tests

### PR DESCRIPTION
**Pull request by ffontaine**
Allow the user to explicitly disable tests

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by jgalar** [comment]
What is the rationale for this change?

**Comment by ffontaine** [comment]
A faster compilation time and avoiding build failures on downstream projects (such as buildroot). For example, we have the following build failure on riscv32 glibc toolchains because `SYS_ppoll `and  `SYS_pselect6` are undeclared:

```
make[4]: Entering directory '/home/giuliobenetti/autobuild/run/instance-1/output-1/build/lttng-tools-2.12.3/tests/regression/kernel'
  CC       select_poll_epoll-select_poll_epoll.o
select_poll_epoll.c: In function 'ppoll_fds_buffer_overflow':
select_poll_epoll.c:408:16: error: 'SYS_ppoll' undeclared (first use in this function); did you mean 'SYS_tkill'?
  408 |  ret = syscall(SYS_ppoll, ufds, 100, NULL, NULL);
      |                ^~~~~~~~~
      |                SYS_tkill
select_poll_epoll.c: In function 'pselect_invalid_fd':
select_poll_epoll.c:488:16: error: 'SYS_pselect6' undeclared (first use in this function); did you mean 'SYS_semctl'?
  488 |  ret = syscall(SYS_pselect6, fd + 1, &rfds, NULL, NULL, NULL, NULL);
      |                ^~~~~~~~~~~~
      |                SYS_semctl
```

Full build log is available here: http://autobuild.buildroot.org/results/dd3/dd39188a7191efa512a51f18f4c34d9ee711a6a7/build-end.log

**Comment by ffontaine** [comment]
Do you have additional comments? An other option would be to disable lttng-tools on riscv32 if you don't want to support this architecture.

**Comment by PSRCode** [comment]
Hi,

While we do not officially support riscv32 (on our CI at least), considering only this tests compilation seems to be having problem we might want to look into "porting" them, instead of disabling them, and see if lttng break down anywhere else at runtime.

AFAIU risv32 uses __NR_ppoll_time64 and __NR_pselect6_time64. Would you be able to spin up a patch since you seems to  have a bit more context and might have a risv32 system laying somewhere?

That would be really helpful.

Cheers

**Comment by ffontaine** [comment]
Unfortunately, I have no riscv32 system. I'm just sending this patch to fix the failures raised by buildroot autobuilders.

**Comment by PSRCode** [comment]
To be frank, disabling compilation of tests is not really fixing anything here neither for buildroot or lttng in regards to architecture support. You are simply pushing the "problem" under the rug.

Does buildroot run the test suite normally for projects? If not, then feel free to use this patch at buildroot level for now.

Still the patch does make sense in the context that we already disable tests if we are doing a partial build. Exposing `--disable-tests` to give direct control if needed does seems legitimate.

**Comment by arnout** [comment]
In buildroot we don't run tests and also don't build them if it can be avoided. Tests often use features that are not available on niche architectures (even something simple as fork()) so disabling them is a quick-win to make it possible to use a package on such an architecture.

I have no idea why lttng uses syscall instead of simply libc's ppoll and pselect. If you use a direct syscall that uses time_t (or struct timespec), you should always check if the 64-bit version of that syscall is available and use it if it is. This makes sure that you have Y2038 support on all 32-bit architectures. But doing something like that is way too complicated for a drive-by contributor.

**Comment by PSRCode** [comment]
Sure, I understand. Then, feel free to use this patch at buildroot level for now. Keep in mind that we do not offer any semblance of "support" for the riscv32 platform as of today.

We will get around to it at some point.

**Pull request closed without merging**
