### PR TITLE
Convert man pages to AsciiDoc and remove duplicate text in --help outputs

### PR DESCRIPTION
**Pull request by eepp**
This PR splits the lttng(1) man page into one man page per command.

This PR also converts the man pages into AsciiDoc documents.

This PR also updates and improves the contents of each man page.

This PR also makes `lttng COMMAND --help` show the man page of the command `COMMAND`.

This PR also adds a `help` command which does the same thing as `lttng COMMAND --help`.

This PR.

WDYT?

BTW lttng-crash(1), lttng-health-check(3), lttng-relayd(8), and lttng-sessiond(8) are left as is in troff. They should probably be updated to AsciiDoc as well in a subsequent PR, but my focus for this one was lttng(1).

### CODE REVIEW

**Comment by jgalar** [comment]
This PR. It pleases me.

**Comment by eepp** [comment]
Note to @PSRCode: add `--enable-build-man-pages` to the CI jobs for building the man pages. The system needs the `asciidoc` and `xmlto` packages.

**Comment by jgalar** [comment]
Leaving myself a note to make sure that changes to the add-context (application contexts) and stop (no-wait) command are taken into account.

**Comment by eepp** [comment]
@jgalar What's up with the _stop (no-wait) command_ thing?

**Comment by eepp** [comment]
Changes as of this date:

* Updated paragraph about `--no-wait` option in `lttng-stop.1.txt`.
* Converted to AsciiDoc and updated the man pages of `lttng-sessiond`, `lttng-relayd`, and `lttng-crash`.

Should `doc/man/lttng-health-check.3` be converted to AsciiDoc also?

**Comment by jgalar** [comment]
Merged, thanks!

**Pull request closed without merging**
