### PR TITLE
Add status command

### PR DESCRIPTION
**Pull request by eepp**
The status command is the equivalent of:

    lttng [general-options] list <current-session-name>

### CODE REVIEW

**Comment by eepp** [comment]
I'm not editing the man page since there are ongoing efforts to split it and fix it; the `status` command will be documented in this other pull request.

**Comment by jgalar** [comment]
Looks good!

**Comment by jgalar** [comment]
Looks good to me, but this is missing a man page entry. Will you add it as part of your manpage overhaul?

**Comment by eepp** [comment]
> Will you add it as part of your manpage overhaul?

Yes this is the plan.

**Comment by jgalar** [comment]
Image of jgalar
Excellent

**Comment by jgalar** [comment]
Merged, thanks!

**Pull request closed without merging**
